// The post-2007 functions Excel persists with an `_xlfn.` prefix, keyed by their uppercased name.
// OOXML froze its function grammar around Excel 2007; everything Microsoft added since is unknown to
// older readers under its bare name, so the writer stores it prefixed and the reader strips the prefix
// back — the mangling in `formula.ts` is the single place that applies and removes it. That mangler
// treats '.' as part of a function name, so both the plain modern functions and the dotted 2010
// statistical rename family below are matched as whole names and prefixed.
export const MODERN_FUNCTIONS: ReadonlySet<string> = new Set([
  // Dynamic arrays (Excel 365)
  'FILTER',
  'SORT',
  'SORTBY',
  'UNIQUE',
  'SEQUENCE',
  'RANDARRAY',
  'XLOOKUP',
  'XMATCH',
  // LAMBDA and its helpers
  'LAMBDA',
  'LET',
  'BYROW',
  'BYCOL',
  'MAKEARRAY',
  'MAP',
  'REDUCE',
  'SCAN',
  'ISOMITTED',
  // Array shaping (Excel 365)
  'VSTACK',
  'HSTACK',
  'TOROW',
  'TOCOL',
  'WRAPROWS',
  'WRAPCOLS',
  'TAKE',
  'DROP',
  'EXPAND',
  'CHOOSEROWS',
  'CHOOSECOLS',
  // Text (Excel 2019 / 365)
  'TEXTJOIN',
  'CONCAT',
  'TEXTBEFORE',
  'TEXTAFTER',
  'TEXTSPLIT',
  'ARRAYTOTEXT',
  'VALUETOTEXT',
  // Logical and conditional aggregation (Excel 2016 / 2019)
  'IFS',
  'SWITCH',
  'MAXIFS',
  'MINIFS',

  // Other bare-name functions added after the frozen grammar (Excel 2010 / 2013) — trigonometric,
  // bitwise, engineering, information, and math/financial additions. Their names carry no '.', so
  // they need no tokenizer work; they simply have to be recognised as modern to earn the prefix.
  'AGGREGATE',
  'ACOT',
  'ACOTH',
  'COT',
  'COTH',
  'CSC',
  'CSCH',
  'SEC',
  'SECH',
  'ARABIC',
  'BASE',
  'DECIMAL',
  'COMBINA',
  'PERMUTATIONA',
  'GAMMA',
  'GAUSS',
  'PHI',
  'MUNIT',
  'BITAND',
  'BITOR',
  'BITXOR',
  'BITLSHIFT',
  'BITRSHIFT',
  'IMCOSH',
  'IMCOT',
  'IMCSC',
  'IMCSCH',
  'IMSEC',
  'IMSECH',
  'IMSINH',
  'IMTAN',
  'DAYS',
  'ISOWEEKNUM',
  'IFNA',
  'NUMBERVALUE',
  'SHEET',
  'SHEETS',
  'FORMULATEXT',
  'ISFORMULA',
  'ENCODEURL',
  'WEBSERVICE',
  'FILTERXML',
  'UNICHAR',
  'UNICODE',
  'XOR',
  'PDURATION',
  'RRI',

  // The Excel 2010 statistical-consistency rename family and the handful of other post-2007
  // functions whose canonical names contain a '.'. They carry the same `_xlfn.` prefix; the whole
  // dotted name is stored, e.g. `_xlfn.NORM.DIST`, `_xlfn.T.DIST.2T`.
  'BETA.DIST',
  'BETA.INV',
  'BINOM.DIST',
  'BINOM.DIST.RANGE',
  'BINOM.INV',
  'CHISQ.DIST',
  'CHISQ.DIST.RT',
  'CHISQ.INV',
  'CHISQ.INV.RT',
  'CHISQ.TEST',
  'CONFIDENCE.NORM',
  'CONFIDENCE.T',
  'COVARIANCE.P',
  'COVARIANCE.S',
  'EXPON.DIST',
  'F.DIST',
  'F.DIST.RT',
  'F.INV',
  'F.INV.RT',
  'F.TEST',
  'GAMMA.DIST',
  'GAMMA.INV',
  'GAMMALN.PRECISE',
  'HYPGEOM.DIST',
  'LOGNORM.DIST',
  'LOGNORM.INV',
  'MODE.MULT',
  'MODE.SNGL',
  'NEGBINOM.DIST',
  'NORM.DIST',
  'NORM.INV',
  'NORM.S.DIST',
  'NORM.S.INV',
  'PERCENTILE.EXC',
  'PERCENTILE.INC',
  'PERCENTRANK.EXC',
  'PERCENTRANK.INC',
  'POISSON.DIST',
  'QUARTILE.EXC',
  'QUARTILE.INC',
  'RANK.AVG',
  'RANK.EQ',
  'SKEW.P',
  'STDEV.P',
  'STDEV.S',
  'T.DIST',
  'T.DIST.2T',
  'T.DIST.RT',
  'T.INV',
  'T.INV.2T',
  'T.TEST',
  'VAR.P',
  'VAR.S',
  'WEIBULL.DIST',
  'Z.TEST',
  'CEILING.PRECISE',
  'FLOOR.PRECISE',
  'ISO.CEILING',
  'ERF.PRECISE',
  'ERFC.PRECISE',
]);
