// The `Ftab` built-in function table ([MS-XLS] 2.5.198.17, shared verbatim by BIFF12): the index a
// `PtgFunc`/`PtgFuncVar` token carries, mapped to the function name that index means.
//
// A binary formula names no function; it cites one by number, so this table is the whole difference
// between `SUM(A1:A5)` and an unreadable stream. It is transcribed from the normative table rather
// than assembled from Excel's UI, which matters at both ends: the low indices include the XLM macro
// functions (`GOTO`, `ADD.BAR`, …) that no modern sheet uses but a legacy file may still carry, and
// the table simply stops at `RTD`. Everything Microsoft added after that (the whole modern library,
// `TEXTJOIN` through `LAMBDA`) is *not* here and never will be: a post-2007 function is called
// through index 255 ("user defined") with an `_xlfn.`-prefixed name as its first operand, which is
// the same indirection the XML form spells out in the function name itself.
//
// The four gaps (0x00CA–CB, 0x00D9–DA, 0x00F9–FA, 0x014D) are gaps in the specification: those
// indices name no function, so a formula citing one is not decodable rather than decodable as
// something adjacent.

/** The index [MS-XLS] reserves for a call whose name is given by the token stream's first operand. */
export const FTAB_USER_DEFINED = 0x00ff;

/**
 * One built-in function: the name an `iftab` index means, and how many arguments it takes.
 *
 * The arity is not decoration. A `PtgFunc` token states only *which* function is called, never with
 * how many arguments: it is the token Excel emits precisely because the count is implied by the
 * function. So decoding `ROUND(A1,2)` back from its two operands and one call token is impossible
 * without it, and `'variadic'` says the call cannot be spelled with that token at all (`PtgFuncVar`
 * carries its own count; the two token forms partition the table between them). Transcribed from the
 * parameter grammar each function's [MS-XLS] 2.5.198.17 entry states.
 *
 * It used to live in a second table keyed by name, which let an entry exist in one and not the other
 * with nothing to say so. A function whose arity was never transcribed simply read as variadic, and a
 * `PtgFunc` citing it then took the wrong run of operands off the stack and produced a different
 * formula, silently. Recording it beside the name makes "no arity recorded" unrepresentable: the
 * compiler asks for it once per entry, and `'variadic'` becomes a decision written down rather than
 * an absence that looks like one.
 */
export type FunctionEntry = readonly [name: string, arity: number | 'variadic'];

// The table as contiguous runs, each `[first index, entries in order]`. Written this way so the four
// specification gaps are visible as run boundaries instead of hiding as miscounted array entries.
const RUNS: ReadonlyArray<readonly [number, readonly FunctionEntry[]]> = [
  [
    0x0000,
    [
      ['COUNT', 'variadic'],
      ['IF', 'variadic'],
      ['ISNA', 1],
      ['ISERROR', 1],
      ['SUM', 'variadic'],
      ['AVERAGE', 'variadic'],
      ['MIN', 'variadic'],
      ['MAX', 'variadic'],
      ['ROW', 'variadic'],
      ['COLUMN', 'variadic'],
      ['NA', 0],
      ['NPV', 'variadic'],
      ['STDEV', 'variadic'],
      ['DOLLAR', 'variadic'],
      ['FIXED', 'variadic'],
      ['SIN', 1],
      ['COS', 1],
      ['TAN', 1],
      ['ATAN', 1],
      ['PI', 0],
      ['SQRT', 1],
      ['EXP', 1],
      ['LN', 1],
      ['LOG10', 1],
      ['ABS', 1],
      ['INT', 1],
      ['SIGN', 1],
      ['ROUND', 2],
      ['LOOKUP', 'variadic'],
      ['INDEX', 'variadic'],
      ['REPT', 2],
      ['MID', 3],
      ['LEN', 1],
      ['VALUE', 1],
      ['TRUE', 0],
      ['FALSE', 0],
      ['AND', 'variadic'],
      ['OR', 'variadic'],
      ['NOT', 1],
      ['MOD', 2],
      ['DCOUNT', 3],
      ['DSUM', 3],
      ['DAVERAGE', 3],
      ['DMIN', 3],
      ['DMAX', 3],
      ['DSTDEV', 3],
      ['VAR', 'variadic'],
      ['DVAR', 3],
      ['TEXT', 2],
      ['LINEST', 'variadic'],
      ['TREND', 'variadic'],
      ['LOGEST', 'variadic'],
      ['GROWTH', 'variadic'],
      ['GOTO', 1],
      ['HALT', 'variadic'],
      ['RETURN', 'variadic'],
      ['PV', 'variadic'],
      ['FV', 'variadic'],
      ['NPER', 'variadic'],
      ['PMT', 'variadic'],
      ['RATE', 'variadic'],
      ['MIRR', 3],
      ['IRR', 'variadic'],
      ['RAND', 0],
      ['MATCH', 'variadic'],
      ['DATE', 3],
      ['TIME', 3],
      ['DAY', 1],
      ['MONTH', 1],
      ['YEAR', 1],
      ['WEEKDAY', 'variadic'],
      ['HOUR', 1],
      ['MINUTE', 1],
      ['SECOND', 1],
      ['NOW', 0],
      ['AREAS', 1],
      ['ROWS', 1],
      ['COLUMNS', 1],
      ['OFFSET', 'variadic'],
      ['ABSREF', 2],
      ['RELREF', 2],
      ['ARGUMENT', 'variadic'],
      ['SEARCH', 'variadic'],
      ['TRANSPOSE', 1],
      ['ERROR', 'variadic'],
      ['STEP', 0],
      ['TYPE', 1],
      ['ECHO', 'variadic'],
      ['SET.NAME', 'variadic'],
      ['CALLER', 0],
      ['DEREF', 1],
      ['WINDOWS', 'variadic'],
      ['SERIES', 'variadic'],
      ['DOCUMENTS', 'variadic'],
      ['ACTIVE.CELL', 0],
      ['SELECTION', 0],
      ['RESULT', 'variadic'],
      ['ATAN2', 2],
      ['ASIN', 1],
      ['ACOS', 1],
      ['CHOOSE', 'variadic'],
      ['HLOOKUP', 'variadic'],
      ['VLOOKUP', 'variadic'],
      ['LINKS', 'variadic'],
      ['INPUT', 'variadic'],
      ['ISREF', 1],
      ['GET.FORMULA', 1],
      ['GET.NAME', 'variadic'],
      ['SET.VALUE', 2],
      ['LOG', 'variadic'],
      ['EXEC', 'variadic'],
      ['CHAR', 1],
      ['LOWER', 1],
      ['UPPER', 1],
      ['PROPER', 1],
      ['LEFT', 'variadic'],
      ['RIGHT', 'variadic'],
      ['EXACT', 2],
      ['TRIM', 1],
      ['REPLACE', 4],
      ['SUBSTITUTE', 'variadic'],
      ['CODE', 1],
      ['NAMES', 'variadic'],
      ['DIRECTORY', 'variadic'],
      ['FIND', 'variadic'],
      ['CELL', 'variadic'],
      ['ISERR', 1],
      ['ISTEXT', 1],
      ['ISNUMBER', 1],
      ['ISBLANK', 1],
      ['T', 1],
      ['N', 1],
      ['FOPEN', 'variadic'],
      ['FCLOSE', 1],
      ['FSIZE', 1],
      ['FREADLN', 1],
      ['FREAD', 2],
      ['FWRITELN', 2],
      ['FWRITE', 2],
      ['FPOS', 'variadic'],
      ['DATEVALUE', 1],
      ['TIMEVALUE', 1],
      ['SLN', 3],
      ['SYD', 4],
      ['DDB', 'variadic'],
      ['GET.DEF', 'variadic'],
      ['REFTEXT', 'variadic'],
      ['TEXTREF', 'variadic'],
      ['INDIRECT', 'variadic'],
      ['REGISTER', 'variadic'],
      ['CALL', 'variadic'],
      ['ADD.BAR', 'variadic'],
      ['ADD.MENU', 'variadic'],
      ['ADD.COMMAND', 'variadic'],
      ['ENABLE.COMMAND', 'variadic'],
      ['CHECK.COMMAND', 'variadic'],
      ['RENAME.COMMAND', 'variadic'],
      ['SHOW.BAR', 'variadic'],
      ['DELETE.MENU', 'variadic'],
      ['DELETE.COMMAND', 'variadic'],
      ['GET.CHART.ITEM', 'variadic'],
      ['DIALOG.BOX', 1],
      ['CLEAN', 1],
      ['MDETERM', 1],
      ['MINVERSE', 1],
      ['MMULT', 2],
      ['FILES', 'variadic'],
      ['IPMT', 'variadic'],
      ['PPMT', 'variadic'],
      ['COUNTA', 'variadic'],
      ['CANCEL.KEY', 'variadic'],
      ['FOR', 'variadic'],
      ['WHILE', 1],
      ['BREAK', 0],
      ['NEXT', 0],
      ['INITIATE', 2],
      ['REQUEST', 2],
      ['POKE', 3],
      ['EXECUTE', 2],
      ['TERMINATE', 1],
      ['RESTART', 'variadic'],
      ['HELP', 'variadic'],
      ['GET.BAR', 'variadic'],
      ['PRODUCT', 'variadic'],
      ['FACT', 1],
      ['GET.CELL', 'variadic'],
      ['GET.WORKSPACE', 1],
      ['GET.WINDOW', 'variadic'],
      ['GET.DOCUMENT', 'variadic'],
      ['DPRODUCT', 3],
      ['ISNONTEXT', 1],
      ['GET.NOTE', 'variadic'],
      ['NOTE', 'variadic'],
      ['STDEVP', 'variadic'],
      ['VARP', 'variadic'],
      ['DSTDEVP', 3],
      ['DVARP', 3],
      ['TRUNC', 'variadic'],
      ['ISLOGICAL', 1],
      ['DCOUNTA', 3],
      ['DELETE.BAR', 1],
      ['UNREGISTER', 1],
    ],
  ],
  [
    0x00cc,
    [
      ['USDOLLAR', 'variadic'],
      ['FINDB', 'variadic'],
      ['SEARCHB', 'variadic'],
      ['REPLACEB', 4],
      ['LEFTB', 'variadic'],
      ['RIGHTB', 'variadic'],
      ['MIDB', 3],
      ['LENB', 1],
      ['ROUNDUP', 2],
      ['ROUNDDOWN', 2],
      ['ASC', 1],
      ['DBCS', 1],
      ['RANK', 'variadic'],
    ],
  ],
  [
    0x00db,
    [
      ['ADDRESS', 'variadic'],
      ['DAYS360', 'variadic'],
      ['TODAY', 0],
      ['VDB', 'variadic'],
      ['ELSE', 0],
      ['ELSE.IF', 1],
      ['END.IF', 0],
      ['FOR.CELL', 'variadic'],
      ['MEDIAN', 'variadic'],
      ['SUMPRODUCT', 'variadic'],
      ['SINH', 1],
      ['COSH', 1],
      ['TANH', 1],
      ['ASINH', 1],
      ['ACOSH', 1],
      ['ATANH', 1],
      ['DGET', 3],
      ['CREATE.OBJECT', 'variadic'],
      ['VOLATILE', 'variadic'],
      ['LAST.ERROR', 0],
      ['CUSTOM.UNDO', 'variadic'],
      ['CUSTOM.REPEAT', 'variadic'],
      ['FORMULA.CONVERT', 'variadic'],
      ['GET.LINK.INFO', 'variadic'],
      ['TEXT.BOX', 'variadic'],
      ['INFO', 1],
      ['GROUP', 0],
      ['GET.OBJECT', 'variadic'],
      ['DB', 'variadic'],
      ['PAUSE', 'variadic'],
    ],
  ],
  [
    0x00fb,
    [
      ['RESUME', 'variadic'],
      ['FREQUENCY', 2],
      ['ADD.TOOLBAR', 'variadic'],
      ['DELETE.TOOLBAR', 1],
      ['User Defined Function', 'variadic'],
      ['RESET.TOOLBAR', 1],
      ['EVALUATE', 1],
      ['GET.TOOLBAR', 'variadic'],
      ['GET.TOOL', 'variadic'],
      ['SPELLING.CHECK', 'variadic'],
      ['ERROR.TYPE', 1],
      ['APP.TITLE', 'variadic'],
      ['WINDOW.TITLE', 'variadic'],
      ['SAVE.TOOLBAR', 'variadic'],
      ['ENABLE.TOOL', 3],
      ['PRESS.TOOL', 3],
      ['REGISTER.ID', 'variadic'],
      ['GET.WORKBOOK', 'variadic'],
      ['AVEDEV', 'variadic'],
      ['BETADIST', 'variadic'],
      ['GAMMALN', 1],
      ['BETAINV', 'variadic'],
      ['BINOMDIST', 4],
      ['CHIDIST', 2],
      ['CHIINV', 2],
      ['COMBIN', 2],
      ['CONFIDENCE', 3],
      ['CRITBINOM', 3],
      ['EVEN', 1],
      ['EXPONDIST', 3],
      ['FDIST', 3],
      ['FINV', 3],
      ['FISHER', 1],
      ['FISHERINV', 1],
      ['FLOOR', 2],
      ['GAMMADIST', 4],
      ['GAMMAINV', 3],
      ['CEILING', 2],
      ['HYPGEOMDIST', 4],
      ['LOGNORMDIST', 3],
      ['LOGINV', 3],
      ['NEGBINOMDIST', 3],
      ['NORMDIST', 4],
      ['NORMSDIST', 1],
      ['NORMINV', 3],
      ['NORMSINV', 1],
      ['STANDARDIZE', 3],
      ['ODD', 1],
      ['PERMUT', 2],
      ['POISSON', 3],
      ['TDIST', 3],
      ['WEIBULL', 4],
      ['SUMXMY2', 2],
      ['SUMX2MY2', 2],
      ['SUMX2PY2', 2],
      ['CHITEST', 2],
      ['CORREL', 2],
      ['COVAR', 2],
      ['FORECAST', 3],
      ['FTEST', 2],
      ['INTERCEPT', 2],
      ['PEARSON', 2],
      ['RSQ', 2],
      ['STEYX', 2],
      ['SLOPE', 2],
      ['TTEST', 4],
      ['PROB', 'variadic'],
      ['DEVSQ', 'variadic'],
      ['GEOMEAN', 'variadic'],
      ['HARMEAN', 'variadic'],
      ['SUMSQ', 'variadic'],
      ['KURT', 'variadic'],
      ['SKEW', 'variadic'],
      ['ZTEST', 'variadic'],
      ['LARGE', 2],
      ['SMALL', 2],
      ['QUARTILE', 2],
      ['PERCENTILE', 2],
      ['PERCENTRANK', 'variadic'],
      ['MODE', 'variadic'],
      ['TRIMMEAN', 2],
      ['TINV', 2],
    ],
  ],
  [
    0x014e,
    [
      ['MOVIE.COMMAND', 'variadic'],
      ['GET.MOVIE', 'variadic'],
      ['CONCATENATE', 'variadic'],
      ['POWER', 2],
      ['PIVOT.ADD.DATA', 'variadic'],
      ['GET.PIVOT.TABLE', 'variadic'],
      ['GET.PIVOT.FIELD', 'variadic'],
      ['GET.PIVOT.ITEM', 'variadic'],
      ['RADIANS', 1],
      ['DEGREES', 1],
      ['SUBTOTAL', 'variadic'],
      ['SUMIF', 'variadic'],
      ['COUNTIF', 2],
      ['COUNTBLANK', 1],
      ['SCENARIO.GET', 'variadic'],
      ['OPTIONS.LISTS.GET', 1],
      ['ISPMT', 4],
      ['DATEDIF', 3],
      ['DATESTRING', 1],
      ['NUMBERSTRING', 2],
      ['ROMAN', 'variadic'],
      ['OPEN.DIALOG', 'variadic'],
      ['SAVE.DIALOG', 'variadic'],
      ['VIEW.GET', 'variadic'],
      ['GETPIVOTDATA', 'variadic'],
      ['HYPERLINK', 'variadic'],
      ['PHONETIC', 1],
      ['AVERAGEA', 'variadic'],
      ['MAXA', 'variadic'],
      ['MINA', 'variadic'],
      ['STDEVPA', 'variadic'],
      ['VARPA', 'variadic'],
      ['STDEVA', 'variadic'],
      ['VARA', 'variadic'],
      ['BAHTTEXT', 1],
      ['THAIDAYOFWEEK', 1],
      ['THAIDIGIT', 1],
      ['THAIMONTHOFYEAR', 1],
      ['THAINUMSOUND', 1],
      ['THAINUMSTRING', 1],
      ['THAISTRINGLENGTH', 1],
      ['ISTHAIDIGIT', 1],
      ['ROUNDBAHTDOWN', 1],
      ['ROUNDBAHTUP', 1],
      ['THAIYEAR', 1],
      ['RTD', 'variadic'],
    ],
  ],
];

// Indexed by `iftab`; a hole is an index the specification does not define.
//
// Assigned into a bare array rather than built with `flat()`, so the gaps are genuinely absent
// entries rather than present-and-undefined ones, which is what lets the transcription test tell the
// two apart.
const TABLE: (FunctionEntry | undefined)[] = [];
for (const [start, entries] of RUNS) {
  entries.forEach((entry, offset) => {
    TABLE[start + offset] = entry;
  });
}

/** The built-in function an `iftab` index names, or `undefined` if the index names none. */
export function builtinFunctionAt(index: number): FunctionEntry | undefined {
  return TABLE[index];
}

/** Look up a built-in function name by its `iftab` index, or `undefined` if the index names none. */
export function functionNameFor(index: number): string | undefined {
  return TABLE[index]?.[0];
}

// Exported for the transcription test beside this file, and for nothing else. Six hundred names typed
// out of a normative table have exactly one failure mode, a slip in the typing, and it is invisible at
// runtime: a name in the wrong slot still decodes, just to a different function, for every formula
// citing that index. Nothing checked the transcription, so the test asserts what the specification
// says about the table's shape rather than recomputing it from the runs it is written as.
export const FTAB: readonly (FunctionEntry | undefined)[] = TABLE;
